---
all:
  hosts:
    control:
      node_ip: 172.22.22.130
    master1:
      node_ip: 172.22.22.131
    node1:
      node_ip: 172.22.22.132
    node2:
      node_ip: 172.22.22.133
    node3:
      node_ip: 172.22.22.134
    storage:
      node_ip: 172.22.22.137
